# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
fortran: false
latex: false

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew install curl
        - brew link --force curl

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
  on_success: change
on_failure: change
